version: "3.9"
services:
  yata:
    image: asia-north1-docker.pkg.dev/<PROJECT_ID>/yata-agent/yata-agent:latest
    container_name: yata-agent
    restart: always
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      CLIENT_SECRETS_JSON: "${CLIENT_SECRETS_JSON}"
      REDIRECT_URI: "https://example.com/oauth2callback"
      DB_PATH: "/data/yata_agent.db"
    volumes:
      - recordings:/var/yata/recordings
      - db-data:/data
    ports:
      - "8000:8000"  # FastAPI が待ち受けるポート
volumes:
  recordings:
    driver: local
  db-data:
    driver: local